### ISSUE TITLE
putObject() response is not consumed, leaking resources

### ISSUE THREAD

**Issue by topperspal** [bradenmacdonald/deno-s3-lite-client#18] opened 2023-06-10 05:38 UTC
```
error: Leaking resources:
  - A fetch response body (rid 15) was created during the test, but not consumed during the test. Consume or close the response body `ReadableStream`, e.g `await resp.text()` or `await resp.body.cancel()`.

 ```

**Comment by bradenmacdonald** [comment] 2023-06-10 18:16
Can you please provide a reproducible example?

[This test](https://github.com/bradenmacdonald/deno-s3-lite-client/blob/c3493090067a4cc54aeb0636189b7c9b2752b990/integration.ts#L67-L73) uses `putObject()` and should indicate if any resources are leaking, but it passes without errors. Perhaps you can modify it to match your case?

Also, please double-check that you are `await`ing the result of `putObject()`. It's a simple mistake that [Deno doesn't warn you about](https://github.com/denoland/deno_lint/issues/303), but it would cause an error like this.

**Comment by bradenmacdonald** [comment] 2023-10-13 03:43
Closing as can't reproduce, unless I hear otherwise.

**Closed by bradenmacdonald** 2023-10-13 03:43 UTC
